### PR TITLE
Shortened module names.

### PR DESCRIPTION
**Pull request by nealholl**
I'm preparing to clean up these files, and wanted to start with the names. "Capacitor" was abbreviated in the file and module names as per the KCL. Note that no changes were made to the 3D models.  If this is acceptable, then I will proceed with changes to bring the footprints in line with the KLC.

### CODE REVIEW

**Comment by michal777** [comment]
Hi.
Do you use find and replace and renaming tools?
What do you think about name starting with C_... (just like in Capacitors_SMD). If you want to rename the footprints please rename also 3d models (rename files in packages3d/ and replace "(model Capacitors_ThroughHole/Capacitor..." with "(model Capacitors_ThroughHole/C_...").

**Comment by michal777** [comment]
And question (to anybody who knows): what is "RM" in name (why it's called so)?

**Comment by keruseykaryu** [comment]
> And question (to anybody who knows): what is "RM" in name (why it's called so)?

The RM stands for leads pitch raster. I don't know exactly which from this acronym comes, but I suppose it is "Raster in Millimeters".
The most popular rasters in foil capacitors are: RM7.5 - 7.5mm between the center of the circular pins, RM10 - 10mm, RM15 - 15mm and RM22 - 22mm.

**Comment by nealholl** [comment]
Sorry about the spammed commits. I'm still trying to learn Git/Github.

I used a quick and dirty Python script to make these changes. I can provide it if anyone would like it.

I've made the advised changes, and gone with C_... In the KLC, it is always noted "Cap...", so I assumed that was prefered. Perhaps the conventions should be modified to use the prefered version? Also, I've modified the 3D model files names, and generated a pull request (I hope I've done that right...)

It's good to know about the "RM", though I'm a bit confused why not use "P" for "Pitch" and leave off units unless they are not in mm?

**Comment by michal777** [comment]
Will you change also Capacitors_Elko_ThroughHole? It would be better to move all electrolytic capacitors to one library and use one naming scheme. The problem with these two libraries is that length and diameter are in different order which may be more difficult to rename. It's also hard to guess which of these walues are length, which is diameter and what is RM so maybe it should be clarified - eg.:
Capacitor10x16RM5 -> C_D10_L16_P5mm
or
Capacitor10x16RM5 -> C_Dia10_Len16_Pitch5mm

**Comment by nealholl** [comment]
I'll suggest a naming pattern for radial packages of:
C_Radial_D(Diameter in mm)_L(Length in mm)_P(Pitch in mm)
for axial packages of:
C_Axial_D(Diameter in mm)_L(Length in mm)_P(Pitch in mm)
 and for ceramic discs as:
C_Disc_D(Diameter in mm)_T(Thickness in mm)_P(Pitch in mm)

I believe the measurement units have been (more or less) standardized on mm, correct? If that's the case, then the "mm" can be implicit. This eliminates the confusion of diameter vs. length vs. pitch and what the mounting orientation is. I can easily script most these conversions, once it's settled on.

My preference would be to merge the to two folders into one, and just eliminate "Capacitors_Elko_ThroughHole". I would also like to remove the mixing of languages (I gather that "elko" is German?)

**Comment by keruseykaryu** [comment]
I think the __RM__ should remain. It is widely used in catalogs, electronics stores, etc. So it will be will be more recognizable by the designers and hobbyist than the __P__.

**Comment by michal777** [comment]
Electrolytic capacitors:
a - TDK
S - CDE
F - ELNA, CHEMI-CON, PANASONIC, RUBYCON
P - NICHICON, KEMET
In ICs: e
RM is probably used in connectors (?)
I don't know which is better, maybe "Pitch" (long but understandable)?

**Comment by CarlPoirier** [comment]
Capacitors_Elko_ThroughHole definitely has to disappear. C_* is great since it is the reference designator anyway. The KLC does give the example of "Cap_*", but that can be adjusted. The naming scheme you suggested is good. BTW, thanks for undertaking this!

**Comment by nealholl** [comment]
I've renamed the files to mostly match the pattern I suggested, as well as added in the "elko" files. At this points, the "elko" files are all there and have a similar name, but include the post-fix descriptors. With that said, I would anticipate removing some of the modules as they do not appear appropriate for a core library (e.g. footprints designed to be used for parts with either 5mm or 7.5mm lead spacing). 

The two changes that I made to the naming were to not include a "thickness" on disc capacitors. This is not ideal, but I haven't found a "standard" thickness for ceramic disc caps, and I'm not sure what the target thickness of the current files is supposed to be. This may change as I make alterations to the footprints themselves.

The second change was to add another naming category for footprints with a rectangular shape. It follows the same basic pattern I presented before, so is:
C_Rect_L(Length in mm)_W(Width in mm)_P(Pitch in mm)

**Comment by michal777** [comment]
I can see you left old elko... and .py scripts in .pretty library. "RevB" can be removed from names.

**Comment by nealholl** [comment]
Hopefully things are a bit cleaner now. We'll get there eventually....

**Comment by michal777** [comment]
Could you move + in C_Radial_D14_L31.5_P5 to silkscreen?
I agree that not all elko... should be added, it's rather not necessary to keep another verision with + on copper (rarely used, usually obstacle).
Maybe it's better to keep universal footprints here or move them to other library.
@Carl - what do you think about moving them to Resistors_Univarsal and renaming library to Universal?

**Comment by CarlPoirier** [comment]
I agree with the Universal.pretty library.

As for polarity, you might want to have the same scheme for all capacitors. I'd go for indicating the negative lead.

**Comment by nealholl** [comment]
My intention is to make a number of adjustments to the footprints, not the least of which is unifying how polarization is indicated. My current plan for the radial capacitors is to have pad 1 be square and pad 2 be round, have the outline be filled on the negative lead half, and possibly include a '+' outside of outline. For now, I'll probably leave the silkscreen alone on the axial capacitors.

These changes are in addition to moving pin 1 to the origin, adding a courtyard and adjusting drill/pad sizes to match IPC-7251 level B standards. There are some other general 'cleanup' type things that I'll probably be doing along the way. Unfortunately, all of this is taking a decent bit of time to make happen.

**Comment by nealholl** [comment]
I went ahead and merged in all the fixes I've been making to the footprints. Hopefully, it's all sensible and in line with the KLC. Another set of eyes on this would be good to make sure I didn't miss anything, I could have easily overlooked something.

**Comment by michal777** [comment]
C_Rect_L18_W5_P15 has no courtyard.
Most of 3d models don't match footprints. If footprint was shifted/rotated proper Shape Offset (usually 0.5*pith [inch]) and Shape Rotation should be set.

**Comment by nealholl** [comment]
All of the existing 3D models should  now lineup correctly with the pads. There were also one or two problems that I fixed with footprints along the way. There are a few footprints without 3D models, but I have not learned any modeling software well enough to be able to generate them yet.

**Comment by michal777** [comment]
Looks good. Will you make more changes or you want it to be merged as is?

I'm not sure about the silkscreen - IPC-7351C prohibits putting any silkscreen under component and silkscreen isn't visible after assembly. My ideas for further improvements are: 1. Move silkscreen to assembly layer (to save drawing illustrating dimensions), 2. Make courtyard thicker and move to silkscreen (then probably it will be visible after assembly), 3. Add + visible after assembly on silkscreen, 4. Add new courtyard by some scripts, 5. Optionally some of 3D models can be replaced with improved revisions available on http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm

**Comment by nealholl** [comment]
I did not plan on making any additional substantive changes. If there are fixes, I would be happy to do that.

When I placed the courtyard I attempted to follow the draft recommendations in IPC-7251, and did not want to extend the silk beyond the courtyard (another semi-conflicting requirement of IPC-7351C). I believe we are at a case where one guideline or the other must be broken. I opted to go the route that improved space efficiency, which is congruent with using the 'nominal' and not 'most' conditions for the land/drill and courtyard dimensions. With that said, there is certainly a reasonable argument for defaulting to the 'most' footprint and following the suggestions that have been put forward.

It is possible to include the most, nominal, and least footprints, though it does tend to clutter the library. If that is desirable, I would suggest separate libraries to house the three levels of manufacturability/compactness. The 3D models could be common, and the footprints could be optimized for each condition.

As for the 3D models, they are a nicety that I find myself caring very little about. There are many other things that I rank higher on the priority list than validating and adjusting additional 3D models.

**Comment by michal777** [comment]
It was decided that level B should be used in kicad libraries so now I can see that you are right that it may be hard to make silkscreen visible after assembly and keep recommendations from IPC-7251. If you don't plan to make more changes I'm for merging although we must wait for Carl's opinion about your changes in silkscreen for radial capacitors because it breaks the rule that it should be visible.

**Comment by nealholl** [comment]
I have no additional changes planned.

**Comment by CarlPoirier** [comment]
Hey,

Your changes look very great. In the KLC, we specified that the outline has to be visible after the assembly, which does not exclude markings in the center from being hidden. Michal was waiting for me to merge this, so I'll do it now.

Thanks @nealholl, @michal777 and @keruseykaryu.

**Pull request merged**
