### PR TITLE
fixed Tantal capacitors scaling for new models

### PR DESCRIPTION
**Pull request by Shackmeister**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Can you please "untouch" the files that have not had the scaling updated? i.e. a lot of files have only had the timestamp changed -please remove these from the commit.

**Comment by Shackmeister** [comment]
@SchrodingersGat should be done now

**Comment by SchrodingersGat** [comment]
Thanks :) This is easier to review and also means that timestamps only change if there is a change to the FP.

Have models been submitted for this yet?

**Comment by Shackmeister** [comment]
I agree :) models will be submitted in 2 min

**Comment by Shackmeister** [comment]
https://github.com/KiCad/kicad-library/pull/1475
https://github.com/KiCad/packages3D/pull/106

**Comment by SchrodingersGat** [comment]
Thanks :)

**Pull request merged**
