### PR TITLE
Added capacitor with 18mm diamter, 36mm height 7.5mm pitch.

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by keruseykaryu** [comment]
I don't know what's wrong with your copy of KiCad, but every time when we ask You to move the anchor the only thing that changes in the updated .kicad_mod file(s) is the "time stamp".

**Comment by crackerizer** [comment]
I also notice that too. I use kicad on ubuntu and install it from a PPA. It seems to me that you can't just put the anchor at pin 1. You have to make some change to the footprint so the origin will move to pin 1. I usually create a footprint and move the anchor after. I will try to change my workflow by fixing the anchor at pin 1 before the footprint is done.

**Comment by crackerizer** [comment]
I have mod the footprint according to KLC.

**Comment by CarlPoirier** [comment]
Good to go, thanks!

**Pull request merged**
